# -*- coding: utf-8 -*-
"""PLOTS_PardoDaniel_S6C2_EDO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xfyasRwMXRxErJCqPiOAYLEmUCkbIGPA
"""

import numpy as np
import matplotlib.pyplot as plt

misdatos = np.loadtxt('misdatosEULER.dat', delimiter = "," )
misdatosRunge = np.loadtxt('misdatosRunge.dat', delimiter = "," )
print(len(misdatos),len(misdatos[0]))
print(len(misdatosRunge),len(misdatosRunge[0]))
#print(misdatos)
#print(misdatos[:,0]) #primera columna

t=misdatos[:,0]
y_euler=misdatos[:,1]
y_runge=misdatosRunge[:,1]
y_solanalitica = np.exp(-1*t)

plt.plot(t, y_euler, label='Euler')
plt.plot(t, y_runge, label='Runge-Kutta')
plt.scatter(t, y_solanalitica, marker = "*",label='Solución Analítica')
plt.xlabel('t')
plt.ylabel('y')
plt.title('Comparación de Euler vs Solución Analítica')
plt.legend()
plt.grid(True)
plt.savefig("eulerpng.png")

